version: '3.9'

services:
  redis:
    ports:
      - 127.0.0.1:6379:6379
  app:
    user: '1000'
    volumes:
      - ./:/app
    ports:
      - 127.0.0.1:9229:9229
    environment:
      NODE_ARGS: --inspect=0.0.0.0:9229
    command: ['yarn', '_docker']
